#%RAML 1.0
title: Pay.gov Experience API
description: Notice this API provides an abstraction layer atop some pay.gov REST web services endpoints. Users can leverage this API to simplify the user experience for their applications looking to integrate directly with Pay.gov. In order to implement this API, one must initiate the process of requesting access to the pay.gov web services and then build out the integration directly to pay.gov. Our hope is this API provides boot-straps that process by providing pre-defined data elements as well as related documentation published in the associated white paper.
/payments/payment:
  post:
    displayName: Initiate Payment
    description: This endpoint represents the payment initiation process. Upon successful invocation of this endpoint, the system will return a token that can be used to complete the transaction.
    body:
      application/json:
        type: paymentRequest
    responses:
      "200":
        body:
          application/json:
            properties:
              token:
                description: This token is used in subsequent API calls to complete the transaction
                example: 1234567abcdefg
                type: string
types:
  paymentRequest:
    description: This object represents the payment request
    properties:
      accountHolderName:
        description: Name of account holder associated with pay.gov account
        example: John Doe
        type: string
      agencyTrackingId:
        description: This field is a *client* generated ID used to track payments.
        example: A7CD1256
        type: string
      customFields:
        description: Represents custom fields created as part of the setup to integrate with pay.gov
        properties:
          customField1:
            example: "#PONumber"
            type: string
          customField2:
            example: InternalReferenceKey3
            type: string
      email:
        description: email associated with pay.gov integration account
        example: jdoe@agency.gov
        type: string
      paymentType:
        example: PLASTIC_CARD
        type: string
      transactionAmount:
        example: 55.37
        type: number
        format: float
      transactionType:
        example: Authorization
        type: string
      urlCancel:
        example: http://www.example.com/cancel
        type: string
      urlSuccess:
        example: http://www.example.com/success
        type: string
  paymentDetails:
    description: This object represents payment details
    properties:
      agencyTrackingId:
        description: "This field is a *client* generated ID used to track payments. "
        example: ABCD-EF-gh1234567I
        type: string
      paygovTrackingId:
        description: Tracking ID generated by Pay.gov
        example: 12A3B456
        type: string
      transactionStatus:
        example: SUCCESS
        type: string
      transactionAmount:
        example: 55.37
        type: number
        format: float
      maskedAccountNumber:
        example: "************5063"
        type: string
      customFields:
        properties:
          customField1:
            properties:
              CF1:
                example: AgencyCustomField
                type: string
      returnCode:
        example: 1
        type: number
        format: int
      returnDetail:
        example: Successful
        type: string
      accountHolderName:
        example: John Doe
        type: string
      transactionDate:
        example: 2024-10-22T18:42:46
        type: datetime-only
      billingInfo:
        properties:
          billingAddress:
            example: 123 Main Street
            type: string
          billingCity:
            example: McLean
            type: string
          billingState:
            example: VA
            type: string
          billingZip:
            example: 22102
            type: number
            format: int
          billingCountry:
            example: US
            type: string
/payments/payment/{agencyTrackingId}:
  get:
    displayName: Get Payment Details
    queryParameters:
      agencyId:
        description: "Unique ID client's agency. This is provided by the Pay.gov team as part of the onboarding process. "
        example: "1234"
        type: string
      applicationId:
        description: "The ID of client application. This is provided by the Pay.gov team as part of the onboarding process. "
        example: ABC123
        type: string
    responses:
      "200":
        body:
          application/json:
            type: paymentDetails
  uriParameters:
    agencyTrackingId:
      description: "This field is a *client* generated ID used to track payments. "
      example: ABCD-EF-gh1234567I
      type: string
/payments/payment-auth/{agencyTrackingId}/capture:
  post:
    displayName: Complete Payment
    body:
      application/json:
        properties:
          token:
            description: This token is generated by the payment initiation flow
            example: 1234567abcdefg
            type: string
    responses:
      "200":
        body:
          application/json:
            properties:
              paymentTrackingID:
                example: Example
                type: string
  uriParameters:
    agencyTrackingId:
      description: "This field is a *client* generated ID used to track payments. "
      example: ABCD-EF-gh1234567I
      type: string
